# Generated by Django 5.2.7 on 2025-10-07 15:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Categoria')),
                ('propiedad', models.CharField(default='General', max_length=100, verbose_name='Propiedad o Tipo')),
                ('icono', models.ImageField(blank=True, null=True, upload_to='categorias/', verbose_name='Ícono de la Categoría')),
                ('activa', models.BooleanField(default=True, verbose_name='¿Está Activa?')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Ticket')),
                ('descripcion', models.TextField(verbose_name='Descripción del Problema')),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('PROCESO', 'En Proceso'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=10, verbose_name='Estado Actual')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('adjunto', models.ImageField(blank=True, null=True, upload_to='tickets/', verbose_name='Adjuntar Evidencia')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.categoria', verbose_name='Categoría Asignada')),
            ],
        ),
    ]
